const assert=require('node:assert/strict'),path=require('node:path'),{EventEmitter}=require('node:events')
const root=path.resolve(__dirname,'..')
const registry=require(path.join(root,'node_modules/prismarine-registry'))('1.20.1')
const Chunk=require(path.join(root,'node_modules/prismarine-chunk'))('1.20.1')
const {Vec3}=require(path.join(root,'node_modules/vec3'))
const chunk=new Chunk(),lava=new Vec3(2,-20,2),debris=new Vec3(4,-19,4)
chunk.setBlockStateId(lava,registry.blocksByName.lava.minStateId)
chunk.setBlockStateId(debris,registry.blocksByName.ancient_debris.minStateId)
const bot=new EventEmitter()
Object.assign(bot,{registry,game:{minY:-64},entity:{position:new Vec3(0,-20,0),yaw:0,pitch:0},username:'Test',players:{},world:{getColumns:()=>[{chunkX:0,chunkZ:0,column:chunk}],getColumn:()=>chunk}})
;(async()=>{
  const radar=require(path.join(root,'radar'))(bot)
  for(let attempt=0;radar.snapshot().scanPending&&attempt<100;attempt++)await new Promise(setImmediate)
  const state=radar.snapshot()
  assert(state.ores.some(b=>b.name==='lava'&&b.position.y===-20))
  assert(state.ores.some(b=>b.name==='ancient_debris'))
  const filtered=radar.filtered(chunk)
  assert.equal(filtered.getBlockStateId(lava),0)
  assert.equal(filtered.getBlockStateId(debris),chunk.getBlockStateId(debris))
  bot.emit('blockUpdate',{name:'lava',position:lava},{name:'air',position:lava})
  assert(!radar.snapshot().ores.some(b=>b.name==='lava'))
  console.log('PASS: lava ESP below Y=0, ancient debris detection, lava removal updates cache, xray stays ore-only')
})().catch(error=>{console.error(error);process.exitCode=1})
